### ISSUE TITLE
기본 데이터베이스 설계 + ORM

### ISSUE THREAD

**Issue by upa-r-upa** [upa-r-upa/taskie_backend#22]
## TODO

- 기본 구조만 작성하도록 합니다
- [x]  ORM
    - [x]  유저
    - [x]  투두
    - [x]  습관
    - [x]  루틴
    - [x]  투두-루틴 관계 테이블
    - [x]  투두-습관 관계 테이블
- [x]  RepeatDays를 처리하는 법
- [x]  역참조 넣기
- [x]  Cascade 넣기
- [x]  ORM을 토대로 DB 초기화하기

**Comment by upa-r-upa** [comment]
# 추가로 필요한 테이블 브레인스토밍
    - 뽀모도로 설정 (미정)
        - 뽀모도로 시간
        - 쉬는 시간
        - 긴 쉬는 시간
        - 긴 쉬는 시간의 뽀모도로 텀
        - 휴식 자동 시작
        - 다음 뽀모도로 자동 시작
    - 뽀모도로 (미정)
        - id
        - 제목
        - 뽀모도로 시간
        - 쉬는 시간

**Comment by upa-r-upa** [comment]
Resolve by #1
