### ISSUE TITLE
유저 회원가입 기능 제작

### ISSUE THREAD

**Issue by upa-r-upa** [upa-r-upa/taskie_backend#26]
# 작업
- 유저 회원가입 기능을 제작합니다.
# Todo
- [x]  create_app 역참조 에러 해결하기
- [x]  API 파고 제대로 나오는지 확인하기 (Swagger)
- [x]  회원가입 기능 예시 좀만 찾아보기
- [x]  데이터 모델 만들기
- [x]  회원가입 입-출력 형태 고민하기
    ## 입력
    
    - id
    - 비밀번호
    - 비밀번호 확인 값
    - 이름
    - 닉네임 → 옵셔널 값
    - email (중복 확인) → 옵셔널 값
- [x]  구현하기
- [x]  에러 처리하기
    - [x]  db exception 일괄 처리하기
- [x]  유효성 검사하기
    - [x]  필수값 검사
    - [x]  비밀번호 체크
    - [x]  이미 존재하는 email
    - [x]  이미 존재하는 id
- [x]  암호화 처리 하기

**Comment by upa-r-upa** [comment]
Resolved by #2
