### ISSUE TITLE
Flask를 FastAPI로 migration 진행

### ISSUE THREAD

**Issue by upa-r-upa** [upa-r-upa/taskie_backend#30]
# 작업
- Flask를 FastAPI로 migration 진행합니다.

# 이유
- 기존에도 Flask와 FastAPI를 고민했었는데, 그때는 간단하게 요약해서 Flask가 작은 서비스를 개발하는 것에 있어서 더 편하다는 결론이 나서 결정했었음.
    - 근데 Flask를 사용하면서 문법적으로 불편함을 느낌.
    - API를 제작할 때 꽤 중요하다고 생각하는 Validator 툴을 적용하면서 마음 먹음.
        - WTForms 라던지, marshmallow와 같은 툴을 찾아서 적용하려고 했었음.
        - 그 중 가장 마음에 들었던 게 pydantic 이었음.
        - validator를 추가하는 방식과 모델을 선언하는 방식 등이 가장 컴팩트하다고 느껴서 사용하고 싶었음.
- 그래서 Flask에 적용을 하다보니까, 원하는대로 세팅하려고 하니.. **결국 내가 원하는 건 FastAPI의 모습과 가장 흡사하다는 걸 깨달음.**
    - FastAPI는 pydantic이 내장되어 있음 + 문법 편함 + 세팅 필요 없음 + 이미 작성해둔 코드 별로 없음
    - → 원한다면 지금이 마이그레이션을 진행할 때라고 판단.
    - → 찾아보니 Flask에서 FastAPI로 가는 사람들도 비슷한 이유로 가는 것 같음.
- 그렇게 해서 이관하기로 했습니다.

# Todo

- [x]  바꾸는 김에 Poerty로 설정하기
- [x]  Gitignore 수정하기
- [x]  flask_sqlalchemy에서 sqlalchemy로 변경하기
    - 기본 설정 문서 찾아보고 수정하기
    - [x]  API 코드 수정하기
- [x]  JWT_extended에서 PyJWT로 변경하기
    - 기본 설정 문서 찾아보고 수정하기
    - [x]  기본 설정 하기
        - JWT identify를 추가해서 토큰을 만들고 - decode 하는 걸 만들어야 겠다
    - [x]  Flask jwt extended 코드 궁금한데.. 뭔 역할을 해주고 있었던거지??
        - 그냥 사용하기 편하게 해주는 래퍼 느낌임.
    - [x]  에러 종류는 어떻케 하는게 좋을까?
- [x]  migration folder는 그대로 유지가 되는걸까?
- [x]  Migration
- [x]  안 켜지는 에러 수정
- [x]  에러 세팅
- [x]  user API 수정
- [x]  todo API 수정

**Comment by upa-r-upa** [comment]
Resolved by #8
