### ISSUE TITLE
Python 테스트 환경 세팅

### ISSUE THREAD

**Issue by upa-r-upa** [upa-r-upa/taskie_backend#37]
# 작업 내용
- 작업을 진행하다 보니.. API 하나를 추가하고 나면 테스트를 위해 일련의 작업을 해야합니다.
    - 로그인 하고,
    - 로그인 한 계정으로 확인용 데이터 추가하고,
    - 데이터를 통한 Action을 여러번 반복하고,
    - 하면서 수정된 데이터를 항상 조회해보고..
    - 원하는대로 동작하는지 확인.
- 그래서 귀찮다보니 슬슬 테스트에 대해서 생각해보게 됩니다.
- 그리고 가장 핵심적인 이유로는, Flask → FastAPI로 마이그레이션을 진행할 때
    - 마이그레이션을 진행하고 API가 제대로 동작할 지
    - 싹 다 다시 테스트 해보면서 너무 불편했습니다.
    - 그래서 지금이 테스트 프레임워크를 추가할 때다 생각하고 추가하려고 합니다.
# 테스트 프레임워크 고민
## 참고한 문서
[[unittest vs pytest](https://www.bangseongbeom.com/unittest-vs-pytest.html)](https://www.bangseongbeom.com/unittest-vs-pytest.html)

## 툴 고민
- unitest
    - 꼭 필요한 문법만 있음
    - 정석적임
    - 클래스 위주라 좀 쳐야하는게 많음
- pytest
    - 문법이 특이함
    - 본인들만의 문법이라 이해 힘들수 있음
    - 하지만 편리한 문법
    - 뭐가 많음 

## 결정

- 최종적으로 pytest로 결정했습니다.
- 좀 더 대중적인 것 같고, 초반엔 복잡하더라도 익숙해졌을 때 편리한 문법을 좀 더 선호합니다.

# Todo
- [x]  상대경로 문제 해결하기
- [x]  테스트 환경 세팅
- [x]  테스트 코드 세팅 잘 됐는지 하나 작성해보기
- [x]  아차 디비 테스트도..

**Comment by upa-r-upa** [comment]
Resolved by #9
